/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as ProjectsSkyJoyRouteImport } from './routes/projects.sky-joy'
import { Route as ProjectsPyramidAmaraRouteImport } from './routes/projects.pyramid-amara'
import { Route as ProjectsNagpurMarinaRouteImport } from './routes/projects.nagpur-marina'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSkyJoyRoute = ProjectsSkyJoyRouteImport.update({
  id: '/projects/sky-joy',
  path: '/projects/sky-joy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPyramidAmaraRoute = ProjectsPyramidAmaraRouteImport.update({
  id: '/projects/pyramid-amara',
  path: '/projects/pyramid-amara',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNagpurMarinaRoute = ProjectsNagpurMarinaRouteImport.update({
  id: '/projects/nagpur-marina',
  path: '/projects/nagpur-marina',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/nagpur-marina': typeof ProjectsNagpurMarinaRoute
  '/projects/pyramid-amara': typeof ProjectsPyramidAmaraRoute
  '/projects/sky-joy': typeof ProjectsSkyJoyRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/nagpur-marina': typeof ProjectsNagpurMarinaRoute
  '/projects/pyramid-amara': typeof ProjectsPyramidAmaraRoute
  '/projects/sky-joy': typeof ProjectsSkyJoyRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/nagpur-marina': typeof ProjectsNagpurMarinaRoute
  '/projects/pyramid-amara': typeof ProjectsPyramidAmaraRoute
  '/projects/sky-joy': typeof ProjectsSkyJoyRoute
  '/property/$id': typeof PropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/nagpur-marina'
    | '/projects/pyramid-amara'
    | '/projects/sky-joy'
    | '/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/nagpur-marina'
    | '/projects/pyramid-amara'
    | '/projects/sky-joy'
    | '/property/$id'
  id:
    | '__root__'
    | '/'
    | '/projects/nagpur-marina'
    | '/projects/pyramid-amara'
    | '/projects/sky-joy'
    | '/property/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsNagpurMarinaRoute: typeof ProjectsNagpurMarinaRoute
  ProjectsPyramidAmaraRoute: typeof ProjectsPyramidAmaraRoute
  ProjectsSkyJoyRoute: typeof ProjectsSkyJoyRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/sky-joy': {
      id: '/projects/sky-joy'
      path: '/projects/sky-joy'
      fullPath: '/projects/sky-joy'
      preLoaderRoute: typeof ProjectsSkyJoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/pyramid-amara': {
      id: '/projects/pyramid-amara'
      path: '/projects/pyramid-amara'
      fullPath: '/projects/pyramid-amara'
      preLoaderRoute: typeof ProjectsPyramidAmaraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/nagpur-marina': {
      id: '/projects/nagpur-marina'
      path: '/projects/nagpur-marina'
      fullPath: '/projects/nagpur-marina'
      preLoaderRoute: typeof ProjectsNagpurMarinaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsNagpurMarinaRoute: ProjectsNagpurMarinaRoute,
  ProjectsPyramidAmaraRoute: ProjectsPyramidAmaraRoute,
  ProjectsSkyJoyRoute: ProjectsSkyJoyRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
